{
 "title": "sensor_dashBoard",
 "time": { "from": "2025-06-22T17:39:37.806Z", "to": "2025-06-28T10:11:37.806Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PROXIMIDADE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  sensor_proximidade as proximidade,\r\nFROM sistema_veicular_sensor\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "PROXIMIDADE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  sensor_proximidade as proximidade,\r\n  airbag as airbag\r\nFROM sistema_veicular_sensor\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\n"
    }
   ]
  },
  {
   "title": "TEMPERATURA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  temperatura as temperatura,\r\nFROM sistema_veicular_temperatura\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "TEMPERATURA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  temperatura as temperatura,\r\nFROM sistema_veicular_temperatura\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "ACELERACAO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  aceleracao as aceleracao,\r\nFROM sistema_veicular_acelerador\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "FREIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  sensor_freio as sensor_freio\r\nFROM sistema_veicular_freio\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "VELOCIDADE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  velocidade as velocidade\r\nFROM sistema_veicular_acelerador\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "ACELERAÇÃO/FREIO/VELOCIDADE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  aceleracao as aceleracao,\r\n  velocidade as velocidade\r\nFROM sistema_veicular_acelerador\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    },
    {
     "rawSql": "SELECT\r\n  timestamp AS \"tempo\",\r\n  sensor_freio as sensor_freio\r\nFROM sistema_veicular_freio\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC"
    }
   ]
  }
 ]
}